package com.gt7telemetry

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Validates the hand-rolled Salsa20 against keystream generated by
 * PyCryptodome (an independent, widely-used implementation) with the actual
 * GT7 key and the GT7 nonce construction. If the cipher core, word order or
 * counter handling drift, these bytes stop matching.
 */
class Salsa20Test {

    private val key = "Simulator Interface Packet GT7 ver 0.0"
        .toByteArray(Charsets.US_ASCII).copyOf(32)

    private fun nonceFor(iv1: Int): ByteArray {
        val nonce = ByteArray(8)
        ByteBuffer.wrap(nonce).order(ByteOrder.LITTLE_ENDIAN)
            .putInt(iv1 xor 0xDEADBEAF.toInt())
            .putInt(iv1)
        return nonce
    }

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { ((s[it * 2].digitToInt(16) shl 4) or s[it * 2 + 1].digitToInt(16)).toByte() }

    @Test
    fun `keystream matches PyCryptodome for the GT7 key + nonce scheme`() {
        // Salsa20.new(key=KEY, nonce=LE(iv1^0xDEADBEAF)+LE(iv1)).encrypt(0x00*64)
        // with iv1 = 0x12345678.
        val expected = hex(
            "e761213d5ee1f35e1f1e7eeebd89834618ea7403795ab10b46e16357f013a4e0" +
                "fa87a81822addccf1b60daf1e777d31ded16c8cef2da66bbaed7b79378806a87"
        )
        val ks = Salsa20.xor(ByteArray(64), 64, key, nonceFor(0x12345678))
        assertArrayEquals(expected, ks)
    }

    @Test
    fun `xor twice is the identity across block boundaries`() {
        val plain = ByteArray(296) { (it * 7 + 3).toByte() }
        val nonce = nonceFor(-0x21524111) // 0xDEADBEEF
        val enc = Salsa20.xor(plain, plain.size, key, nonce)
        val dec = Salsa20.xor(enc, enc.size, key, nonce)
        assertArrayEquals(plain, dec)
        // And the keystream isn't degenerate.
        assertEquals(false, enc.contentEquals(plain))
    }
}
